
name: Maven Package

on:
 push:
 pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'
        cache: 'maven'
    - name: Build cask API
      run: mvn -B package --file cask-api/pom.xml
    - name: Upload the cask API artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: cask-api-0.1.jar
        path: cask-api/target/cask-api-0.1.jar
